version: "3.9"

networks:
  nginx-proxy:
      name: nginx-proxy

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 81:81
    networks:
      - nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/html:/user/share/nginx/html
    links:
      - frontend-react
      - backend-nest
  
  backend-nest:
    container_name: form-back
    image: formjson-back
    ports:
      - 3000:3000
    networks:
      - nginx-proxy
    volumes:
      - ./www/FormJSON-Back:/usr/share/nginx/html

  frontend-react:
    container_name: form-front
    image: formjson-front
    ports:
      - 5173:5173
    networks:
      - nginx-proxy
    volumes:
      - ./www/FormJSON-Front:/usr/share/nginx/html